# Generated by Django 4.2.10 on 2025-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_customer_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlesale',
            name='municipal_service_code',
            field=models.CharField(blank=True, help_text='Código de serviço municipal para a emissão da nota fiscal', max_length=10, null=True, verbose_name='Código de Serviço Municipal'),
        ),
    ]
