# Generated by Django 4.2.10 on 2025-05-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_customer_address_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlesale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nota Avulsa', 'verbose_name_plural': 'Notas Avulsas'},
        ),
        migrations.AddField(
            model_name='singlesale',
            name='codigo_servico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Serviço'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='gerar_boleto',
            field=models.BooleanField(default=False, verbose_name='Gerar Boleto'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='recorrencia',
            field=models.CharField(blank=True, choices=[('none', 'Nenhuma'), ('monthly', 'Mensal'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannually', 'Semestral'), ('annually', 'Anual')], default='none', max_length=20, null=True, verbose_name='Recorrência para Nota e Boleto'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='vencimento_boleto',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento do Boleto'),
        ),
    ]
