# Generated by Django 5.0.10 on 2025-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_customer_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlesale',
            name='municipal_service_code',
            field=models.CharField(blank=True, help_text='Código de serviço municipal para emissão de notas fiscais (ex: 0107, 14.01)', max_length=10, null=True, verbose_name='Código de Serviço Municipal'),
        ),
    ]
