# Generated by Django 4.2.10 on 2025-05-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_singlesale_options_singlesale_codigo_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlesale',
            name='codigo_servico',
        ),
        migrations.RemoveField(
            model_name='singlesale',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='singlesale',
            name='gerar_boleto',
        ),
        migrations.RemoveField(
            model_name='singlesale',
            name='recorrencia',
        ),
        migrations.RemoveField(
            model_name='singlesale',
            name='vencimento_boleto',
        ),
    ]
