# Generated by Django 4.2.10 on 2025-07-10 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_singlesale_municipal_service_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlesale',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='emission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='has_recurrence',
            field=models.BooleanField(default=False, verbose_name='Possui Recorrência'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='É Recorrente'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='parent_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_sales', to='payments.singlesale', verbose_name='Venda Pai'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='recurrence_count',
            field=models.IntegerField(default=0, help_text='0 = sem recorrência, 1-12 = meses de recorrência', verbose_name='Quantidade de Recorrências'),
        ),
        migrations.AddField(
            model_name='singlesale',
            name='recurrence_number',
            field=models.IntegerField(default=0, help_text='0 = venda original', verbose_name='Número da Recorrência'),
        ),
    ]
