# Generated by Django 4.2.10 on 2025-09-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_singlesale_due_date_singlesale_emission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlesale',
            name='recurrence_count',
            field=models.IntegerField(default=0, help_text='0 = sem recorrência, 1-24 = meses de recorrência', verbose_name='Quantidade de Recorrências'),
        ),
    ]
