# Generated by Django 4.2.10 on 2025-07-31 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('AGENDA', 'Agenda'), ('CURSOS', 'Cursos'), ('FINANCAS', 'Finanças'), ('CLIENTES', 'Clientes')], max_length=20, verbose_name='módulo')),
                ('has_access', models.BooleanField(default=True, verbose_name='tem acesso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'permissão de módulo',
                'verbose_name_plural': 'permissões de módulos',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
