# Generated by Django 4.2.10 on 2025-05-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do aluno no formato XXX.XXX.XXX-XX', max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
