# Generated by Django 4.2.10 on 2025-05-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line',
            field=models.CharField(blank=True, help_text='Rua, Avenida, etc.', max_length=255, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_number',
            field=models.CharField(blank=True, help_text='Número do endereço', max_length=10, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='UF do estado (ex: SP, RJ)', max_length=2, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, help_text='CEP no formato XXXXX-XXX', max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
