# Generated by Django 4.2.10 on 2025-05-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_amount_invoice_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('processing', 'Processando'), ('issued', 'Emitida'), ('approved', 'Aprovada'), ('cancelled', 'Cancelada'), ('error', 'Erro')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
