# Generated by Django 4.2.10 on 2025-05-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='city_service_code',
            field=models.CharField(default='0107', help_text='Código de serviço específico do município para atividades educacionais', max_length=10, verbose_name='código de serviço municipal'),
        ),
    ]
