# Generated by Django 4.2.10 on 2025-06-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_companyconfig_city_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='city_service_code',
            field=models.CharField(default='0107', help_text='Código de serviço padrão do município para atividades educacionais', max_length=10, verbose_name='código de serviço municipal padrão'),
        ),
        migrations.CreateModel(
            name='MunicipalServiceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de serviço específico do município', max_length=10, verbose_name='código de serviço')),
                ('description', models.CharField(blank=True, help_text='Descrição opcional do serviço', max_length=255, null=True, verbose_name='descrição')),
                ('company_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_codes', to='invoices.companyconfig', verbose_name='configuração da empresa')),
            ],
            options={
                'verbose_name': 'código de serviço municipal',
                'verbose_name_plural': 'códigos de serviço municipal',
                'unique_together': {('company_config', 'code')},
            },
        ),
    ]
