# Generated by Django 5.0.10 on 2025-05-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_companyconfig_city_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='city_service_code',
            field=models.CharField(default='0107', help_text='Campo mantido para compatibilidade. Use os códigos de serviço relacionados.', max_length=10, verbose_name='código de serviço municipal (legado)'),
        ),
        migrations.CreateModel(
            name='ServiceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de serviço municipal (ex: 0107, 1401, etc.)', max_length=10, verbose_name='código de serviço')),
                ('description', models.CharField(help_text='Descrição do tipo de serviço prestado', max_length=255, verbose_name='descrição do serviço')),
                ('is_default', models.BooleanField(default=False, help_text='Marque como padrão para usar automaticamente em novas notas', verbose_name='código padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('company_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_codes', to='invoices.companyconfig', verbose_name='configuração da empresa')),
            ],
            options={
                'verbose_name': 'código de serviço',
                'verbose_name_plural': 'códigos de serviço',
                'ordering': ['code'],
                'unique_together': {('company_config', 'code')},
            },
        ),
    ]
