# Generated by Django 4.2.10 on 2025-05-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_companyconfig_city_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='city_service_code',
            field=models.TextField(default='["0107"]', help_text='Códigos de serviço específicos do município para atividades educacionais. Clique em + para adicionar mais códigos.', verbose_name='códigos de serviço municipal'),
        ),
    ]
