# Generated by Django 4.2.10 on 2025-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_companyconfig_city_service_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='city_service_code',
            field=models.CharField(help_text='Código de serviço padrão do município para atividades educacionais', max_length=10, verbose_name='código de serviço municipal padrão'),
        ),
    ]
