# Generated by Django 4.2.10 on 2025-08-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_companyconfig_city_service_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='nfeio_api_key',
            field=models.CharField(blank=True, help_text='Chave de API específica para esta empresa no NFE.io', max_length=255, null=True, verbose_name='Chave API NFE.io'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='nfeio_company_id',
            field=models.CharField(blank=True, help_text='ID específico da empresa cadastrada na plataforma NFE.io', max_length=50, null=True, verbose_name='ID da empresa no NFE.io'),
        ),
    ]
