# Generated by Django 4.2.10 on 2025-06-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_companyconfig_city_service_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePixPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(help_text='ID único para identificar o pagamento Pix', max_length=255, unique=True, verbose_name='ID de correlação')),
                ('brcode', models.TextField(blank=True, help_text='Código Pix copia e cola', null=True, verbose_name='BR Code Pix')),
                ('qrcode_image_url', models.URLField(blank=True, help_text='URL da imagem do QR Code', max_length=500, null=True, verbose_name='URL do QR Code')),
                ('qrcode_image_data', models.TextField(blank=True, help_text='Dados da imagem QR Code em base64 (fallback)', null=True, verbose_name='QR Code Base64')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor do pagamento em reais', max_digits=10, verbose_name='valor')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data e hora de expiração do Pix', null=True, verbose_name='expira em')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Data e hora do pagamento confirmado', null=True, verbose_name='pago em')),
                ('external_id', models.CharField(blank=True, help_text='ID retornado pela API do provedor Pix', max_length=100, null=True, verbose_name='ID externo')),
                ('provider_response', models.JSONField(blank=True, help_text='Resposta completa da API do provedor Pix', null=True, verbose_name='resposta do provedor')),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro caso ocorra falha', null=True, verbose_name='mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix_payment', to='invoices.invoice', verbose_name='nota fiscal')),
            ],
            options={
                'verbose_name': 'pagamento Pix da nota fiscal',
                'verbose_name_plural': 'pagamentos Pix das notas fiscais',
                'ordering': ['-created_at'],
            },
        ),
    ]
