# Generated by Django 4.2.10 on 2025-08-28 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_add_nfeio_company_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='nfeio_api_key',
        ),
    ]
