# Generated by Django 5.0.10 on 2025-06-02 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_companyclient_cnpj_alter_individualclient_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyclient',
            name='municipal_service_code',
            field=models.CharField(blank=True, help_text='Código de serviço municipal para emissão de notas fiscais (ex: 0107, 14.01)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Digite um código de serviço municipal válido (ex: 0107, 14.01, etc.)', regex='^\\d{2,5}\\.?\\d{0,2}$')], verbose_name='código de serviço municipal'),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='municipal_service_code',
            field=models.CharField(blank=True, help_text='Código de serviço municipal para emissão de notas fiscais (ex: 0107, 14.01)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Digite um código de serviço municipal válido (ex: 0107, 14.01, etc.)', regex='^\\d{2,5}\\.?\\d{0,2}$')], verbose_name='código de serviço municipal'),
        ),
    ]
