# Generated by Django 4.2.10 on 2025-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_companyclient_cnpj_alter_individualclient_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
    ]
