# Generated by Django 4.2.10 on 2025-06-23 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_phone_alter_individualclient_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='responsible_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Digite um CPF válido no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF do responsável'),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome do responsável'),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome fantasia'),
        ),
    ]
