# Generated by Django 4.2.10 on 2025-06-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_individualclient_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='individualclient',
            name='unique_non_null_cpf',
        ),
        migrations.AddConstraint(
            model_name='individualclient',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf__isnull', False), models.Q(('cpf', ''), _negated=True)), fields=('cpf',), name='unique_non_null_cpf'),
        ),
    ]
