# Generated by Django 3.2.20 on 2024-07-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_alter_enrollment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('courses', models.ManyToManyField(blank=True, related_name='class_groups', to='courses.Course', verbose_name='cursos')),
                ('professor', models.ForeignKey(limit_choices_to={'user_type': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL, verbose_name='alunos')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.classgroup', verbose_name='turma'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'class_group')},
        ),
        migrations.CreateModel(
            name='LessonRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(verbose_name='data de liberação')),
                ('is_released', models.BooleanField(default=False, verbose_name='liberada')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_releases', to='courses.classgroup', verbose_name='turma')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='courses.lesson', verbose_name='aula')),
            ],
            options={
                'verbose_name': 'liberação de aula',
                'verbose_name_plural': 'liberações de aulas',
                'ordering': ['release_date'],
                'unique_together': {('class_group', 'lesson')},
            },
        ),
    ] 