# Generated by Django 4.2.10 on 2025-05-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_classgroup_lessonrelease_enrollment_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='private_video_url',
            field=models.URLField(blank=True, help_text='URL para vídeos do play.giancorrea.55jam.com.br', verbose_name='URL do vídeo privado'),
        ),
    ]
