# Generated by Django 4.2.10 on 2025-09-11 14:54

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_private_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.course_image_upload_path, verbose_name='imagem'),
        ),
    ]
