# Generated by Django 4.2.10 on 2025-09-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module__order', 'order', 'created_at'], 'verbose_name': 'aula', 'verbose_name_plural': 'aulas'},
        ),
        migrations.AddField(
            model_name='course',
            name='sequential_modules',
            field=models.BooleanField(default=False, help_text='Se ativado, o aluno só pode acessar o próximo módulo após completar o anterior', verbose_name='módulos sequenciais'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['order', 'created_at'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='módulo'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='concluído')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Porcentagem de aulas concluídas no módulo (0-100)', verbose_name='porcentagem de progresso')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='último acesso em')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progresses', to='courses.enrollment', verbose_name='matrícula')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='courses.module', verbose_name='módulo')),
            ],
            options={
                'verbose_name': 'progresso de módulo',
                'verbose_name_plural': 'progressos de módulos',
                'ordering': ['module__order'],
                'unique_together': {('enrollment', 'module')},
            },
        ),
    ]
