# Generated by Django 4.2.10 on 2025-09-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lesson_options_course_sequential_modules_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
    ]
