# Generated by Django 5.1.4 on 2025-09-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_lesson_module_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('attachment_type', models.CharField(choices=[('PDF', 'PDF'), ('AUDIO', 'Áudio'), ('IMAGE', 'Imagem'), ('DOCX', 'Word'), ('LINK', 'Link'), ('OTHER', 'Outro')], default='OTHER', max_length=10, verbose_name='tipo de anexo')),
                ('file', models.FileField(blank=True, help_text='Upload de arquivo (PDF, áudio, imagem, documento)', null=True, upload_to='lesson_attachments/%Y/%m/', verbose_name='arquivo')),
                ('link', models.URLField(blank=True, help_text='Link externo para o anexo', verbose_name='link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson', verbose_name='aula')),
            ],
            options={
                'verbose_name': 'anexo de aula',
                'verbose_name_plural': 'anexos de aulas',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
